# -*- coding: utf-8 -*-
"""Multiple-Linear-Regression-with-10-Human-Values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGApYUUzMVw-BnRm-OiQpQ-dkL1qRJT3
"""

import pandas as pd
import statsmodels.api as sm
from google.colab import drive

# Montar o Google Drive
drive.mount('/content/drive', force_remount=True)

# URL do Google Sheets
sheet_url = 'https://docs.google.com/spreadsheets/d/13D2YvlGk9pkA9FVZCcvMu4jVpuoSuh7-9dWHA0r_EwE/edit?usp=sharing'
sheet_id = sheet_url.split('/')[5]
exported_url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv'

# Carregar os dados do Google Sheets
df = pd.read_csv(exported_url)

# Verificar se os dados foram importados corretamente
print("Cabeçalho dos dados:")
print(df.head())

# Listar as colunas para confirmar os nomes
print("Colunas no dataset:")
print(df.columns)

# Preparar variáveis preditoras e critério
variaveis_preditivas = [col for col in df.columns if col not in ['Sexo', 'Idade', 'Filhos']]
variavel_criterio = variaveis_preditivas[-1]  # Última coluna como critério
variaveis_preditivas = variaveis_preditivas[:-1]  # Demais como preditoras

# Exibir as variáveis definidas
print(f"Variáveis preditoras: {variaveis_preditivas}")
print(f"Variável critério: {variavel_criterio}")

# Remover valores ausentes
df = df.dropna(subset=variaveis_preditivas + [variavel_criterio])

# Preparar as variáveis para a regressão
X = df[variaveis_preditivas]
y = df[variavel_criterio]

# Adicionar uma constante para o modelo
X = sm.add_constant(X)

# Ajustar o modelo de regressão linear múltipla
modelo = sm.OLS(y, X).fit()

# Exibir os resultados da regressão
print("Resumo da Regressão Linear Múltipla:")
print(modelo.summary())

# Analisar os resultados
r2 = modelo.rsquared
print(f"R² (variância explicada pelo modelo): {r2:.2f}")

# Analisar os coeficientes individuais
print("Coeficientes e significância estatística:")
print(modelo.pvalues)

# Interpretar os resultados
significant_predictors = modelo.pvalues[modelo.pvalues < 0.05].index.tolist()
print(f"Preditores significativos: {significant_predictors}")

# Salvar os resultados no arquivo
output_path = '/content/drive/My Drive/sumario.txt'
with open(output_path, 'w') as f:
    f.write("Resumo da Regressão Linear Múltipla:\n")
    f.write(modelo.summary().as_text())

print(f"Resultados da regressão salvos em: {output_path}")